### ISSUE TITLE
Settings are incorrect in useDocumentVerifier

### ISSUE THREAD

**Issue by Nebulis** [Open-Attestation/identity-wallet#64]
I faced an issue on #63 and I reproduced it from master:

- open the app
- add a log in useDocumentVerifier, for instance before the effect:
```
console.log({ network });
```
- change the network settings to mainnet
- scan a qr code and get the following output

```
Object {
  "network": "ropsten",
}
Object {
  "network": "ropsten",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
Object {
  "network": "mainnet",
}
```

Subsequent scan produce the same result (ropsten first then mainnet) and it leads to some kind of inconsistency in behaviour

**Comment by Nebulis** [comment]
I thought about it last night (don't ask me why 😅).

Problem here is probably that we use hook with a state (iirc) => every time a component is mounted the hook is called and executed and then the previous execution of another hook in another instance if a component is not shared.

Should use context / hook with context instead (and wait for the series state to be loaded before displaying the screen)

**Comment by sebastianquek** [comment]
> Ok looked through this, the issue stems from the config being stale while we wait for the async call to resolve. Using context makes sense. 
>
> So on initial loading of the app, we wait till the config is loaded into the context. Subsequently, useConfig will rely on the context, the updating of AsyncStorage will just be a side effect when setConfig is called.
